"""
Generate data/<key>.txt + manifest.json from data_mapTextData.json.

data_mapTextData.json is the flat corpus array extracted from data.cpp (the
old static corpus). The strings are already cleaned and lowercased (that
happened when data.cpp was originally generated by getKeyFromJson.py).

Run from the repo root:
    python pythonUtilityStuff/generateFromDataJson.py

Outputs:
  data/<key>.txt  — one file per show; captions joined by \n with trailing \n
                    (commitShow in wams.cpp replaces each \n with \0 in-place)
  manifest.json   — [{key, dir, name, lines, bytes, file}, ...] for app.js
"""

import json
import os
import sys

# Show table (same order as getKeyFromJson.py SHOWS, which defines corpus order).
# (start_index, key, img_dir, display_name)
# start_index is the 0-based position of the show's first line in the corpus.
# End of show i = start of show i+1 (or end of array for the last show).
SHOWS = [
    (0,       'sm',          'sm',          'Sailor Moon'),
    (60941,   'cw2003',      'cw2003',      'Clone Wars 2003'),
    (61838,   'swPrequel',   'swPrequel',   'Star Wars Prequels'),
    (65820,   'recess',      'recess',      'Recess'),
    (98080,   'DisPix',      'DisPix',      'Disney Pixar'),
    (142918,  'JohnnyBravo', 'JohnnyBravo', 'Johnny Bravo'),
    (167909,  'ghibli',      'ghibli',      'Ghibli'),
    (194672,  'looneyTunes', 'looneyTunes', 'Looney Tunes'),
    (214152,  'db',          'db',          'Dragon Ball'),
    (245632,  'dbz',         'dbz',         'Dragon Ball Z'),
    (305584,  'dbzMov',      'dbzMov',      'Dragon Ball Z Movies'),
    (314267,  'jojo',        'jojo',        "JoJo's Bizarre Adventure"),
]

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root  = os.path.dirname(script_dir)

    src_json      = os.path.join(repo_root, 'data_mapTextData.json')
    data_dir      = os.path.join(repo_root, 'data')
    manifest_path = os.path.join(repo_root, 'manifest.json')

    if not os.path.exists(src_json):
        sys.exit(f"ERROR: {src_json} not found. Run from the repo root and make sure data_mapTextData.json exists.")

    print(f"Loading {src_json} ...")
    with open(src_json, 'r', encoding='utf-8') as f:
        corpus = json.load(f)
    print(f"  {len(corpus):,} lines loaded")

    os.makedirs(data_dir, exist_ok=True)

    starts = [s[0] for s in SHOWS]
    manifest = []

    for i, (start, key, img_dir, name) in enumerate(SHOWS):
        end   = starts[i + 1] if i + 1 < len(SHOWS) else len(corpus)
        lines = corpus[start:end]

        # captions joined by '\n' + trailing '\n' so commitShow can replace the
        # last '\n' with '\0' and null-terminate the final line in-place.
        content  = '\n'.join(lines) + '\n'
        raw      = content.encode('utf-8')

        out_path = os.path.join(data_dir, f'{key}.txt')
        with open(out_path, 'wb') as f:
            f.write(raw)

        manifest.append({
            'key':   key,
            'dir':   img_dir,
            'name':  name,
            'lines': len(lines),
            'bytes': len(raw),   # exact uncompressed size — drives reserveCorpus
            'file':  f'data/{key}.txt',
        })
        print(f"  {name}: {len(lines):,} lines, {len(raw):,} bytes -> data/{key}.txt")

    with open(manifest_path, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    total_lines = sum(e['lines'] for e in manifest)
    total_bytes = sum(e['bytes'] for e in manifest)
    print(f"\nmanifest.json written ({len(manifest)} shows)")
    print(f"Total: {total_lines:,} lines, {total_bytes:,} bytes ({total_bytes / 1024 / 1024:.1f} MB uncompressed)")

if __name__ == '__main__':
    main()
